"""One still-life subject per category (100). Key: department/category slug. Keep unbranded: no logos, no text."""
SUBJECTS = {
 # plumbing
 "plumbing/pipe-fittings": "Grey PVC and black HDPE pipe lengths with elbows, tees and couplings",
 "plumbing/valves": "A brass ball valve with a red lever, a gate valve and a check valve",
 "plumbing/taps-mixers": "A chrome basin mixer tap and a pair of chrome pillar taps",
 "plumbing/bathroom-toilet": "A chrome shower head and handset, a toilet cistern flush button and a chrome waste outlet",
 "plumbing/geysers": "A white cylindrical electric water heater geyser with copper connections, on its side",
 "plumbing/drainage-rainwater": "Grey PVC drainage pipes with bends and a black rainwater gutter section with a downpipe",
 "plumbing/tanks-hose": "A coil of green garden hose with a brass hose connector and a small float valve",
 "plumbing/sheeting-membranes": "A roll of black builders plastic sheeting and a roll of shiny foil membrane",
 "plumbing/plumbing-consumables-tools": "White PTFE tape, a pipe wrench, a tube of sealant and a hacksaw",
 # electrical
 "electrical/wire-wiring-accessories": "Coils of red, black and green electrical wire with cable ties and conduit clips",
 "electrical/switches-plugs-sockets": "White wall switches, a double socket outlet and a three-pin plug",
 "electrical/circuit-protection-control": "Miniature circuit breakers on a DIN rail beside a contactor and a push-button",
 "electrical/enclosures-db-boards": "An open grey electrical distribution board enclosure with DIN rail and empty breaker slots",
 "electrical/security": "A white dome CCTV camera, a motion sensor and a keypad",
 "electrical/fans-air-movement": "A compact white pedestal fan and a round extractor fan",
 "electrical/contracting-items-electrical-tools": "A wire stripper, a voltage tester screwdriver, a multimeter and cable glands",
 "electrical/maintenance-chemicals": "Aerosol cans and a small bottle of contact cleaner and lubricant, plain unlabelled",
 "electrical/sound-equipment-miscellaneous": "A small black speaker, an extension cord reel and a microphone",
 "electrical/batteries-torches": "A rugged black torch, AA batteries and a rechargeable headlamp",
 # lighting
 "lighting/indoor-led-downlights": "Round aluminium LED downlights glowing warm white",
 "lighting/outdoor-security-lighting": "A black wall-mounted bulkhead light and a brick light glowing at night",
 "lighting/floodlights": "A black LED floodlight casting a wide bright beam",
 "lighting/fluorescent-fittings": "A long white batten tube light fitting with fluorescent tubes",
 "lighting/industrial-lighting": "A round industrial LED high bay light with a metal reflector",
 "lighting/lamps-bulbs": "A row of glass light bulbs: a filament globe, a spiral CFL and an LED bulb",
 "lighting/lamp-holders-spotlights": "A brass lamp holder, a white ceramic bayonet fitting and a track spotlight",
 "lighting/general-lighting": "A simple white ceiling light fitting and a brass pendant with a glowing bulb",
 # solar
 "solar-backup-power/inverters": "A wall-mounted white hybrid solar inverter with a small glowing green status light",
 "solar-backup-power/batteries-energy-storage": "A stack of white lithium battery modules with red accents on a dark floor",
 "solar-backup-power/solar-panels": "A monocrystalline solar panel angled towards warm light",
 "solar-backup-power/kits-backup-power-packages": "A compact solar backup kit: inverter, battery and a folded solar panel together",
 "solar-backup-power/charge-controllers": "A small solar charge controller box with a display and terminals",
 "solar-backup-power/protection-isolators-breakers-fuses": "A DC isolator switch, a solar fuse holder and a DC circuit breaker",
 "solar-backup-power/installation-accessories-cables": "A coil of red and black solar cable, MC4-style connectors and mounting rails",
 "solar-backup-power/monitoring-meters-cts": "A DIN-rail energy meter, a clamp current transformer and a small monitoring dongle",
 "solar-backup-power/solar-lights-dc-appliances": "A solar garden spike light, a DC LED bulb and a small solar-powered fan",
 "solar-backup-power/ev-chargers": "A wall-mounted EV charger with a coiled charging cable and plug, plain unbranded",
 # power tools
 "power-tools/drills-drivers": "A cordless drill and an impact driver with a battery pack",
 "power-tools/grinders": "A corded angle grinder and a cutting disc with sparks flying",
 "power-tools/saws": "A circular saw and a jigsaw side by side",
 "power-tools/sanders-polishers": "An orbital sander with sanding discs and a car polisher",
 "power-tools/rotary-hammers": "A heavy rotary hammer drill with an SDS bit",
 "power-tools/planers-routers": "A handheld electric planer and a plunge router with a router bit",
 "power-tools/welding": "A compact inverter welding machine with a welding cable and electrode holder, and a dark welding helmet",
 "power-tools/water-pumps": "A blue electric water pump and a submersible pump with a hose connection",
 "power-tools/generators-petrol-tools": "A small portable petrol generator with a metal frame",
 "power-tools/batteries-chargers": "Cordless tool battery packs and a charger dock with a green light",
 "power-tools/garden-cleaning": "A cordless grass trimmer and a pressure washer gun with a hose",
 "power-tools/other-power-tools": "A heat gun, a glue gun and a rotary multi-tool",
 "power-tools/drill-bits": "A fan of metal drill bits and masonry drill bits in graduated sizes",
 "power-tools/saw-cutting-blades": "A circular saw blade, a diamond cutting blade and a few jigsaw blades",
 "power-tools/abrasives-sanding": "Sanding discs, sandpaper sheets and flap discs in a neat pile",
 "power-tools/power-bits": "A magnetic bit holder and a row of screwdriver power bits",
 "power-tools/other-accessories": "A chuck key, a depth stop, a dust extraction nozzle and spare brushes",
 # hand tools
 "hand-tools/screwdrivers-sets": "A row of flat and Phillips screwdrivers in a set",
 "hand-tools/pliers-gripping": "Combination pliers, long-nose pliers and a pair of locking pliers",
 "hand-tools/spanners-sockets": "Open-ended spanners and a socket set with a ratchet",
 "hand-tools/hammers-striking": "A claw hammer, a ball-peen hammer and a rubber mallet",
 "hand-tools/chisels-punches": "Wood chisels, a cold chisel and centre punches",
 "hand-tools/measuring-marking": "A tape measure, a spirit level, a set square and a pencil",
 "hand-tools/saws-cutting": "A hand saw, a hacksaw and a utility knife",
 "hand-tools/tin-snips": "Red-handled tin snips and aviation snips",
 "hand-tools/clamps-vices": "A bench vice and G-clamps",
 "hand-tools/finishing-plastering": "A plastering trowel, a float and a paint scraper",
 "hand-tools/garden-tools": "A spade, a hand trowel and pruning shears",
 "hand-tools/tool-storage": "A red metal toolbox and a rolled-up tool pouch with tools",
 "hand-tools/safety-gear": "A hard hat, safety glasses, work gloves and ear defenders",
 "hand-tools/tool-sets-kits": "An open tool case with a mixed set of tools in foam cut-outs",
 "hand-tools/other-hand-tools": "An assortment of hand tools: a crowbar, a file, a hand drill and a wire brush",
 # fixings
 "fixings-adhesives/screws": "Assorted wood and self-tapping screws scattered on steel",
 "fixings-adhesives/nails": "Common nails, masonry nails and a small hammer-ready pile",
 "fixings-adhesives/anchors-wall-plugs": "Red and grey plastic wall plugs and steel expansion anchors",
 "fixings-adhesives/nuts-bolts-washers": "Hex bolts, nuts and flat washers in a neat pile",
 "fixings-adhesives/rivets": "Pop rivets and a hand riveter",
 "fixings-adhesives/threaded-rod": "Lengths of threaded rod with nuts and washers",
 "fixings-adhesives/fastener-kits-pre-packs": "Clear plastic compartment boxes and small packs of assorted fasteners",
 "fixings-adhesives/ironmongery-door-hardware": "A brass door handle, hinges, a padlock and a bolt latch",
 "fixings-adhesives/tapes": "Rolls of masking tape, duct tape and insulation tape",
 "fixings-adhesives/mounting-hanging": "Picture hooks, hanging brackets and a bracket shelf support",
 "fixings-adhesives/weather-sealing": "A sealant cartridge in a caulking gun, a door seal strip and a bead of silicone",
 "fixings-adhesives/bath-household": "A tube of bathroom sealant, a toilet seat hinge and a plug chain",
 # air tools
 "air-tools-compressors/compressors": "A compact air compressor with a tank and pressure gauge",
 "air-tools-compressors/air-tools": "A pneumatic nail gun and an air impact wrench with a coiled hose",
 "air-tools-compressors/spray-guns-airbrushes": "A paint spray gun and a small airbrush",
 "air-tools-compressors/air-treatment": "An air filter regulator unit with a water trap and a gauge",
 "air-tools-compressors/hoses-hose-reels": "A coiled blue air hose and a wall-mounted hose reel",
 "air-tools-compressors/tubing": "Coils of blue and black polyurethane tubing",
 "air-tools-compressors/hose-fittings": "Brass hose barbs, hose clamps and quick couplers",
 "air-tools-compressors/push-in-fittings": "Blue push-in pneumatic fittings: elbows, tees and straight connectors",
 "air-tools-compressors/gauges": "A round pressure gauge and a tyre pressure gauge",
 "air-tools-compressors/vacuum-pumps": "A small vacuum pump with gauges and hose connections",
 # paint
 "paint-waterproofing/interior-paint": "An open tin of cream paint with a wall roller and a brush",
 "paint-waterproofing/exterior-paint": "A large paint tin with a wide brush and a splash of weatherproof paint",
 "paint-waterproofing/roof-paint": "A tin of red roof paint with a long-handled roller",
 "paint-waterproofing/enamel-metal-paint": "A small tin of glossy black enamel with a brush beside a metal gate hinge",
 "paint-waterproofing/wood-care": "A tin of wood stain, a varnish brush and a short length of wooden plank",
 "paint-waterproofing/primers-undercoats-prep": "A tin of white primer, a sanding block and a masking-tape roll",
 "paint-waterproofing/cleaners-strippers": "A spray bottle and a tin of paint stripper with a scraper",
 "paint-waterproofing/waterproofing": "A tin of black bitumen waterproofing and a roll of waterproofing membrane",
 "paint-waterproofing/floor-automotive-industrial": "A tin of grey floor paint, a spray can and a short roller",
}
